import { ActionRequest } from "./pending/RequestsCard";

export const mockAdvisorRequests: ActionRequest[] = [
  {
    id: "REQ-65001",
    name: "สมชาย ใจดี",
    studentId: "65010001",
    major: "พยาบาลศาสตรบัณฑิต",
    year: "3",
    phone: "081-234-5678",
    requestStatus: "รอพิจารณา", 
    objective: "เพื่อชำระค่าลงทะเบียนเรียนภาคการศึกษาที่ 1/2567 เนื่องจากทางบ้านขาดรายได้กะทันหัน",
    amount: "45000",
    term: "2",
    expectedReturnDate: "30 พฤศจิกายน 2567",
    bankDetails: {
      bankName: "ธนาคารไทยพาณิชย์ (SCB)",
      accountNumber: "123-4-56789-0",
      accountName: "นายสมชาย ใจดี",
    },
    submitDate: "15 ส.ค. 2567",
    waitDays: 5,
    isOverdue: false,
    history: [{ action: "ยื่นคำขอกู้ยืม", date: "15 ส.ค. 2567", actor: "สมชาย ใจดี" }],
    paymentBehavior: {
      onTimeStatusLabel: "ชำระตรงเวลา",
      onTimeInstallments: 12,
      lateInstallments: 0,
      totalLoanRequests: 2,
      totalInstallments: 12,
    },
  },
  {
    id: "REQ-66002",
    name: "มานี มีนา",
    studentId: "66010002",
    major: "พยาบาลศาสตรบัณฑิต",
    year: "2",
    phone: "089-876-5432",
    requestStatus: "อนุมัติแล้ว", 
    objective: "เพื่อเป็นค่าใช้จ่ายรายเดือนและค่าอุปกรณ์สำหรับการฝึกปฏิบัติงานบนหอผู้ป่วย",
    amount: "20000",
    term: "3",
    expectedReturnDate: "10 ธันวาคม 2567",
    bankDetails: {
      bankName: "ธนาคารกสิกรไทย (KBANK)",
      accountNumber: "098-7-65432-1",
      accountName: "นางสาวมานี มีนา",
    },
    submitDate: "10 ส.ค. 2567",
    waitDays: 0,
    isOverdue: false,
    history: [
      { action: "ยื่นคำขอกู้ยืม", date: "10 ส.ค. 2567", actor: "มานี มีนา" },
      { action: "อนุมัติคำร้อง", date: "12 ส.ค. 2567", actor: "อ.ที่ปรึกษา" },
    ],
    paymentBehavior: {
      onTimeStatusLabel: "ค้างชำระ",
      onTimeInstallments: 8,
      lateInstallments: 2,
      totalLoanRequests: 3,
      totalInstallments: 10,
    },
  },
  {
    id: "REQ-64003",
    name: "ชูใจ ใฝ่เรียน",
    studentId: "64010003",
    major: "พยาบาลศาสตรบัณฑิต",
    year: "4",
    phone: "082-345-6789",
    requestStatus: "ไม่อนุมัติ", 
    objective: "เพื่อซื้อคอมพิวเตอร์พกพาเครื่องใหม่สำหรับทำวิจัยและโปรเจกต์จบ",
    amount: "35000",
    term: "6",
    expectedReturnDate: "30 มกราคม 2568",
    bankDetails: {
      bankName: "ธนาคารกรุงไทย (KTB)",
      accountNumber: "112-2-33445-5",
      accountName: "นางสาวชูใจ ใฝ่เรียน",
    },
    submitDate: "05 ส.ค. 2567",
    waitDays: 0,
    isOverdue: false,
    history: [
      { action: "ยื่นคำขอกู้ยืม", date: "05 ส.ค. 2567", actor: "ชูใจ ใฝ่เรียน" },
      { action: "ไม่อนุมัติคำร้อง", date: "08 ส.ค. 2567", actor: "อ.ที่ปรึกษา" },
    ],
    paymentBehavior: {
      onTimeStatusLabel: "ชำระตรงเวลา",
      onTimeInstallments: 6,
      lateInstallments: 0,
      totalLoanRequests: 1,
      totalInstallments: 6,
    },
  },
  {
    id: "REQ-67004",
    name: "ปิติ รักดี",
    studentId: "67010004",
    major: "พยาบาลศาสตรบัณฑิต",
    year: "1",
    phone: "091-111-2222",
    requestStatus: "รอพิจารณา", 
    objective: "เพื่อชำระค่าหอพักประจำเดือน เนื่องจากผู้ปกครองส่งเงินให้ไม่ทันกำหนด",
    amount: "8000",
    term: "1",
    expectedReturnDate: "15 กันยายน 2567",
    bankDetails: {
      bankName: "ธนาคารกรุงเทพ (BBL)",
      accountNumber: "555-6-77788-9",
      accountName: "นายปิติ รักดี",
    },
    submitDate: "20 ส.ค. 2567",
    waitDays: 2,
    isOverdue: false,
    history: [{ action: "ยื่นคำขอกู้ยืม", date: "20 ส.ค. 2567", actor: "ปิติ รักดี" }],
    paymentBehavior: {
      onTimeStatusLabel: "กู้ยืมครั้งแรก",
      onTimeInstallments: 0,
      lateInstallments: 0,
      totalLoanRequests: 1,
      totalInstallments: 0,
    },
  },
  {
    id: "REQ-65005",
    name: "วีระ กล้าหาญ",
    studentId: "65010005",
    major: "พยาบาลศาสตรบัณฑิต",
    year: "3",
    phone: "083-444-5555",
    requestStatus: "รอพิจารณา", 
    objective: "เพื่อเป็นค่ารักษาพยาบาลฉุกเฉินจากอุบัติเหตุรถจักรยานยนต์",
    amount: "15000",
    term: "2",
    expectedReturnDate: "30 ตุลาคม 2567",
    bankDetails: {
      bankName: "ธนาคารออมสิน (GSB)",
      accountNumber: "020-3-44556-7",
      accountName: "นายวีระ กล้าหาญ",
    },
    submitDate: "10 ส.ค. 2567",
    waitDays: 12,
    isOverdue: true,
    history: [{ action: "ยื่นคำขอกู้ยืม", date: "10 ส.ค. 2567", actor: "วีระ กล้าหาญ" }],
    paymentBehavior: {
      onTimeStatusLabel: "ชำระตรงเวลา",
      onTimeInstallments: 4,
      lateInstallments: 0,
      totalLoanRequests: 2,
      totalInstallments: 4,
    },
  }
];